name: Build, Push, and Scan Docker Image

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-push-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push docker image
        uses: docker/build-push-action@v4
        with:
          context: ../../
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/agenda:latest

      - name: Set up Trivy
        run: docker pull aquasec/trivy:latest

      - name: Scan Docker image for vulnerabilities and misconfigurations
        run: docker run --rm aquasec/trivy:latest fs --severity HIGH,MEDIUM --exit-code 1 ${{ secrets.DOCKER_USERNAME }}/agenda:latest
